name: Deploy Portfolio Website

# When should this workflow run?
on:
  # Run on push to main branch
  push:
    branches: [ main ]
  # Run on pull requests
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  # Job 1: Test and Build
  build:
    name: Build Website
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
      
      # Step 2: Validate HTML (optional but good practice)
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
        continue-on-error: true  # Don't fail if HTML has minor issues
      
      # Step 3: Upload website files as artifact
      - name: Upload website files
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: website-files
          path: |
            index.html
            styles.css
            script.js

  # Job 2: Deploy to Azure
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build  # Only run after build succeeds
    # Only deploy on push to main (not on PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
      
      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          output_location: "" # Built app content directory
          skip_app_build: true # We're not building anything, just static files